### ISSUE TITLE
Add Support for `IngressClassName`

### ISSUE THREAD

**Issue by riesbl01** [microsoft/K2Bridge#187]
Above TLS in ingress.yaml add input for `ingressClassName: ${{ .Values.ingress.className }}` so ingress controller will pick up ingress and assign LB IP to it.

**Comment by tamirkamara** [comment]
Hi @riesbl01,
It has been awhile since we create the chart... but it does support a Load Balancer (IIRC). 
I assume you have some other use case where our chart isn't ideal, can you share some details with us?

**Comment by riesbl01** [comment]
The helm chart takes values for ingress enabled and host. When doing that its not enough to expose service via ingress since the ingress needs an ingressClassName to be assigned to work. I did this by hand myself after deploying helm chart an able to access the ingress. However, knowing what that exposes now its not important and Id argue that exposing k2bridge externally is not needed. So I am happy to close this PR if you'd like or we can discuss more.

**Comment by tamirkamara** [comment]
Ok, I understand now. So to put things in perspective - we deliberately don't expose the internal components of this solution K2Bridge nor its Elasticsearch since our prime goal is to support Kibana. 
Our deployment suggestion has always been to expose Kibana to users and have a network route for it to communicate with K2Bridge.

If you agree, then please close this issue.
