### ISSUE TITLE
Does K2Bridge work with existing environments?

### ISSUE THREAD

**Issue by joaopf-silva** [microsoft/K2Bridge#192]
Is it possible to use K2Bridge to connect data from an existing Azure table (from a storage account) to an existing Kibana environment?

From what I have read so far and found online, it requires a new Azure Data Explorer cluster and database for K2Bridge work and as well a new Kibana environment.

Has anyone done the same setup I'm aiming to do?

Also, in the [README.md](https://github.com/microsoft/K2Bridge/blob/main/README.md) it refers to supporting Kibana 7, does it support Kibana 8?

**Comment by yogilad** [comment]
With regard to "from an existing Azure table (from a storage account)", 
I'm not sure what you mean by this.
If your data is a set of blob or ADL files which can be represented as an ADX external table, then yes, but if you have data in Azure Storage Tables, Kusto does not support this case.

@AsafMah , can you replay with regard to versions and compatibility?

**Comment by AsafMah** [comment]
Using an existing ADX cluster - of course! just provide the details in the configuration file (including the authentication).

Existing kibana - We support only the open source version of kibana/elastic which stops at 7.10.2 in kibana (and still needs to be the OSS variant of 7.10.2).

If you already have a kibana in the correct version, instead of directing it to an elastic instance, you need to direct it to the k2bridge instance, how to do it depends on how it's installed and configured.
But then the bridge only lets you access the information from kusto instead of the information from elastic, so you probably don't want to do it with an existing installation anyway.

**Comment by joaopf-silva** [comment]
Hi @yogilad , @AsafMah ,

Regarding the environment, yes, I meant Azure Storage Table.
Thank you for your reply.

Our current kibana is also in version 8.6 so it seems to be incompatible.
Thank you once more for your time clarifying the requirements.

**Comment by yogilad** [comment]
You are welcome.
